// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6AX0TErWwL5y1oqGoVQ-6lspLMS9fxOA',
    appId: '1:139232316279:web:8c1eecd3db6ff14efcaf72',
    messagingSenderId: '139232316279',
    projectId: 'app-25-2ccbf',
    authDomain: 'app-25-2ccbf.firebaseapp.com',
    storageBucket: 'app-25-2ccbf.firebasestorage.app',
    measurementId: 'G-D54CDG3L77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsYzvQnkIgr181kptsJXZDsFpWJ1DuIM',
    appId: '1:139232316279:android:50c3808f605254d9fcaf72',
    messagingSenderId: '139232316279',
    projectId: 'app-25-2ccbf',
    storageBucket: 'app-25-2ccbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo7xGp9ZqXcG7IHu5Q2U7207Tz73AMcr0',
    appId: '1:139232316279:ios:d78254931309d222fcaf72',
    messagingSenderId: '139232316279',
    projectId: 'app-25-2ccbf',
    storageBucket: 'app-25-2ccbf.firebasestorage.app',
    iosClientId: '139232316279-q7kks4bp46vmb8m4m9ug032tcqpsr8s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.k2b2Video',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo7xGp9ZqXcG7IHu5Q2U7207Tz73AMcr0',
    appId: '1:139232316279:ios:d78254931309d222fcaf72',
    messagingSenderId: '139232316279',
    projectId: 'app-25-2ccbf',
    storageBucket: 'app-25-2ccbf.firebasestorage.app',
    iosClientId: '139232316279-q7kks4bp46vmb8m4m9ug032tcqpsr8s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.k2b2Video',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6AX0TErWwL5y1oqGoVQ-6lspLMS9fxOA',
    appId: '1:139232316279:web:30b7f854d20ff13efcaf72',
    messagingSenderId: '139232316279',
    projectId: 'app-25-2ccbf',
    authDomain: 'app-25-2ccbf.firebaseapp.com',
    storageBucket: 'app-25-2ccbf.firebasestorage.app',
    measurementId: 'G-9EHJ9Q8MVR',
  );
}
